### ISSUE TITLE
Tracker: New and Existing Tools

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [zopencommunity/meta#922]
List contains a list of new tools to port and/or existing tools to enhance. The demand percentages are based on the last major survey.

## Critical Priority

- [ ] **Vim with Dataset I/O Support**: High demand (26%), critical for bridging traditional and modern workflows.  
  [GitHub Repository](https://github.com/zopencommunity/vimport/tree/copyincopyoutdatasets)  

- [ ] **Coreutils**: High demand (30%), fundamental for UNIX operations on z/OS.  
  - Next step: Determine which tools should have extra z/OS support added.  
  - Break it into different pieces (high-priority items vs. future items).  

- [ ] **Gzip**: Add HW acceleration to speed up deflate.  

- [ ] **Zip/Unzip**: Add HW acceleration to speed up deflate (uses zlib).  

- [ ] **Performance Analysis on Neovim**  

---

## High Priority

- [ ] **rsync (Enhanced)**: High demand (22%), essential for file synchronization in hybrid cloud.  
  - Investigate further to see which cases work and which do not.  

- [ ] **CMake**: Add support for z/OS languages like COBOL, PLI, and PLX.  

- [ ] **Procps (ps, top, watch)**: Moderate demand (15%), supplements existing monitoring tools.  

- [ ] **Neovim**: High demand (20%), improves developer experience + support for LSP.  
  - Performance analysis to determine the culprit.  
  - Build without LuaJIT on Mac or LoZ.  

- [ ] **LuaJIT**: Improves Neovim performance.  

- [ ] **libgcrypt**: Accelerates GPG - Adds HW acceleration to speed up compression/encryption.  

---

## Medium Priority

- [ ] **Gradle**: Moderate demand (13%), enhances build automation.  

- [ ] **nginx**: Moderate demand (10%), critical for hosting web services and APIs.  

- [ ] **CCache**: 18% demand, speeds up build times.  

- [ ] **PostgreSQL**: 13% demand, most advanced open-source database, includes AI functions.  

- [ ] **htop**: Moderate demand (15%), provides real-time resource monitoring.  

- [ ] **Git Extras**: Needed for advanced Git workflows, enhances productivity.  

- [ ] **OpenSSL (Accelerated)**: High demand (18%), leverages z/OS hardware for cryptographic operations.  
  - Curl and Git would benefit from performance improvements.  

- [ ] **Bash Completion**: Improves shell usability.  

- [ ] **Valgrind**: Medium demand (18%), improves debugging and profiling.  
  - A significant effort to port.  

- [ ] **fzf**: Moderate demand (8%), aids in searching through files and directories.  

- [ ] **SSHFS**: Low demand (7%), useful for remote file access over SSH.  

- [ ] **Redis**: Low demand (5%), adds in-memory database capabilities.  

- [ ] **nmap**: Moderate demand (8%), key for network diagnostics and security.  

- [ ] **grpc**: Moderate demand (8%), enables remote procedure calls between services.  

- [ ] **rclone**: Low demand (3%), expands cloud integration capabilities.  
  - Could be a good alternative to rsync.  

- [ ] **Git secret**: [GitHub Repository](https://github.com/sobolevn/git-secret?tab=readme-ov-file)  
  - Enables Git to store encrypted data.  

---

## Low Priority

- [ ] **OpenBLAS**: Low demand, relevant for AI-based inferencing.  

- [ ] **Midnight Commander**: Convenience for file management.  

- [ ] **MySQL**: Low demand (7%), adds RDBMS capabilities but overlaps with other tools.  

- [ ] **Wireshark**: Essential for packet analysis in specific scenarios.  

- [ ] **OpenVPN**: Providing a secure connection on z/OS.  
  [GitHub Repository](https://github.com/OpenVPN/openvpn)

**Comment by v1gnesh** [comment]
@IgorTodorovskiIBM Adding a library that may help with h/w acceleration - https://github.com/intel/isa-l

**Comment by mfsysprog** [comment]
As an alternative to running wireshark there is https://github.com/colinpaicemq/zWireshark or alternatively it is possible to format a tcpip packet trace to pcap format with IPCS. See https://colinpaice.blog/2022/09/29/collecting-a-tcpip-packet-trace-on-z-os/

**Comment by IgorTodorovskiIBM** [comment]
Here's a list of popular packages to consider.
This list was generated by analyzing the "Popular packages" section on Repology (https://repology.org/), a website that tracks software across numerous repositories. Their "spread" metric measures how many repository families (e.g., Debian and its derivatives) include a package, as an indicator of widespread use. 
The list was then compared against current zopen ports, and packages with graphical user interfaces (GUIs) were excluded, to highlight potential gaps in zopen's offerings.

- ansible - IT automation engine (CLI) for configuration management, application deployment, orchestration.
- apache - Widely used open-source HTTP Web Server (Server).
- binutils - Collection of binary tools (linker, assembler, etc.) essential for compiling (CLI Tools).
- cups - Standards-based, open source printing system (Server/Daemon).
- djvulibre - Software (libraries and utilities) for creating, manipulating, and viewing DjVu documents (Library/CLI Tools).
- dosbox - An emulator that recreates a DOS environment, primarily for running old games/software (Emulator/CLI).
- dovecot - Open source IMAP and POP3 email server (Server).
- ffmpeg - A complete, cross-platform solution to record, convert and stream audio and video (CLI/Library).
- fish - A smart and user-friendly command-line shell (CLI Shell).
- gcc - The GNU Compiler Collection, supports C, C++, Objective-C, Fortran, Ada, Go, etc. (CLI Compiler).
- gdb - The GNU Project debugger, allows seeing what is going on inside another program while it executes (CLI Debugger).
- go - Programming language toolchain (compiler, runtime, tools) developed by Google (CLI/Language).
- graphviz - Graph visualization software, takes textual graph descriptions and makes diagrams (CLI/Library).
- grub - GRand Unified Bootloader, commonly used to boot Linux systems (System/Bootloader).
- haproxy - High availability load balancer and proxy server for TCP and HTTP-based applications (Server).
- imagemagick - Software suite to create, edit, compose, or convert bitmap images via command-line (CLI Tools/Library).
- lame - High quality MPEG Audio Layer III (MP3) encoder (CLI Tool/Library).
- llvm - Collection of modular and reusable compiler and toolchain technologies (Compiler Infrastructure/Library/CLI Tools).
- mariadb - Community-developed, commercially supported fork of the MySQL relational database management system (Server + CLI Client).
- maxima - A system for the manipulation of symbolic and numerical expressions, including differentiation, integration, etc. (CLI CAS).
- mc - Midnight Commander, a text-based visual file manager (TUI/CLI Tool).
- mesa - An open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics (Library).
- mutt - Text-based email client known for its power and configurability (TUI/CLI Email Client).
- mysql - Popular open-source relational database management system (Server + CLI Client).
- neofetch - A command-line system information tool (CLI Tool).
- nginx - High-performance HTTP server, reverse proxy, and IMAP/POP3 proxy server (Server).
- nmap - Network Mapper, a utility for network discovery and security auditing (CLI Tool).
- nodejs - Asynchronous event-driven JavaScript runtime, designed to build scalable network applications (Runtime/CLI).
- octave - High-level language, primarily intended for numerical computations (MATLAB alternative) (CLI/Language).
- openvpn - Creates secure point-to-point or site-to-site connections in routed or bridged configurations (VPN Server/Client/CLI).
- p7zip - A command-line port of 7-Zip for POSIX systems, handles many archive formats including 7z (CLI Archiver).
- pip - The package installer for Python (CLI Tool).
- postfix - A free and open-source mail transfer agent (MTA) (Server).
- postgresql - Powerful, open source object-relational database system (Server + CLI Client).
- privoxy - Non-caching web proxy with advanced filtering capabilities for enhancing privacy (Server).
- rust - Systems programming language focused on safety, speed, and concurrency (Compiler/Toolchain/CLI).
- samba - Software suite that provides file and print services for SMB/CIFS clients (Server).
- smartmontools - Utilities for monitoring S.M.A.R.T. (Self-Monitoring, Analysis and Reporting Technology) built into most modern disks (CLI Tools).
- squid - Caching and forwarding HTTP web proxy (Server).
- tor - Software for enabling anonymous communication (Network/Daemon/CLI Tools).
- unbound - Validating, recursive, and caching DNS resolver (Server).
- valgrind - Instrumentation framework for building dynamic analysis tools (Debugging/Profiling/CLI Tools).
- wayland - Communication protocol that specifies the communication between a display server and its clients (Protocol/Library).
- wine - Compatibility layer capable of running Windows applications on several POSIX-compliant operating systems (Compatibility Layer/CLI).
- xterm - Standard terminal emulator for the X Window System (Terminal Emulator/CLI Host).
- yt-dlp - Command-line program to download videos from YouTube and other sites (CLI Tool).
- zeromq - High-performance asynchronous messaging library (Library).
- zsh - A powerful shell with scripting language features (CLI Shell).

**Comment by IgorTodorovskiIBM** [comment]
Macports, an alternative to Brew, also has a analytics available here: https://ports.macports.org/statistics/ports/?days=30&first=-total_count&second=-req_count&third=port

Here's the list of tools/libraries we have not ported:
- brotli (Generic lossless compression algorithm)
- curl-ca-bundle (CA certificates, usually bundled with Curl)
- gnutls (Secure communications library implementing TLS/SSL)
- icu (International Components for Unicode - library for Unicode support)
- kerberos5 (Network authentication protocol library - krb5)
- libdeflate (Library for DEFLATE/zlib/gzip compression/decompression)
- libedit (Command line editing library, alternative to readline)
- libffi (Foreign Function Interface library)
- libidn2 (Library for internationalized domain names in applications)
- libpsl (Library for handling the Public Suffix List)
- libtasn1 (ASN.1 structure parsing library)
- libtextstyle (Text styling library, often associated with gettext)
- libunistring (Library for manipulating Unicode strings)
- lmdb (Lightning Memory-Mapped Database Manager)
- lzo2 (Real-time data compression library)
- nettle (Low-level cryptographic library)
- p11-kit (Library for loading and enumerating PKCS#11 modules)
- readline (Library for command-line editing)

**Comment by IgorTodorovskiIBM** [comment]
Here's the list of Brew Tools (from the top 200 in brew analytics not in zopen):

- ansible - IT automation engine (CLI) for configuration management, application deployment.
- asdf - Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more.
- bat - A cat clone with syntax highlighting and Git integration.
- bun - Fast JavaScript all-in-one toolkit (runtime, bundler, package manager).
- ca-certificates - Common CA certificates repository/package, used for verifying TLS connections.
- ccache - A compiler cache to speed up recompilation by caching previous compilations.
- clang-format - Tool to automatically format C/C++/Java/JavaScript/Objective-C/Protobuf code.
- colima - Container runtimes on macOS (and Linux) with minimal setup, providing Docker/Containerd.
- composer - Dependency Manager for PHP.
- cryptography - Python library which provides cryptographic recipes and primitives.
- ddev - Local PHP (and other languages) development environment system based on Docker Compose.
- deno - A modern runtime for JavaScript and TypeScript.
- docker - Platform for developing, shipping, and running applications in containers.
- docker-compose - Tool for defining and running multi-container Docker applications.
- edencommon - Facebook C++ library providing foundational types and utilities.
- erlang - Programming language runtime used to build massively scalable soft real-time systems.
- eza - A modern replacement for ls with more features and better defaults.
- fastfetch - A neofetch-like tool for fetching system information and displaying it in the terminal.
- fb303 - Facebook Thrift library for basic services infrastructure.
- fbthrift - Facebook's high-performance branch of Apache Thrift (RPC framework).
- ffmpeg - A complete, cross-platform solution to record, convert and stream audio and video.
- fish - A smart and user-friendly command-line shell.
- fizz - Facebook C++ library for implementing TLS 1.3.
- folly - Facebook C++ library containing a variety of core library components used extensively at Facebook.
- freetds - Libraries implementing the Tabular Data Stream (TDS) protocol for MS SQL/Sybase databases.
- gcc - The GNU Compiler Collection (C, C++, Objective-C, Fortran, Ada, Go, etc.).
- go - Programming language toolchain (compiler, runtime, tools) developed by Google.
- go-task - A task runner / build tool aiming to be simpler and easier to use than Make.
- golangci-lint - Fast Go linters runner, aggregating multiple linters.
- gradle - Build automation tool primarily used for JVM languages (Java, Groovy, Scala).
- graphviz - Graph visualization software (CLI tools like dot, neato) that generates diagrams from text descriptions.
- grpcurl - Command-line tool that lets you interact with gRPC servers, like curl but for gRPC.
- guile - An interpreter and compiler for the Scheme programming language.
- gnutls - Secure communications library implementing SSL, TLS and DTLS protocols.
- htop - Interactive process viewer for Unix systems, an alternative to top.
- icu - International Components for Unicode: C/C++ and Java libraries for Unicode support, internationalization, and globalization.
- libffi - Foreign Function Interface library; allows code in one language to call code in another.
- libomp - OpenMP runtime library implementation (often part of the LLVM project).
- libpq - The C application programmer's interface library to PostgreSQL databases.
- lima - Linux virtual machines on macOS (and Linux), useful for running containers or Linux environments.
- llvm - Collection of modular and reusable compiler and toolchain technologies.
- mint - A package manager mainly for installing and running Swift command line tools.
- mise - Development environment manager (formerly rtx), manages tool versions like Node, Python, Ruby, etc.
- mkcert - Simple tool for making locally-trusted development SSL/TLS certificates.
- mongodb-community - MongoDB Community Edition, a popular NoSQL document database server.
- mongosh - MongoDB Shell, an interactive JavaScript and Node.js REPL interface to MongoDB.
- mysql - Popular open-source relational database management system (server & client).
- nginx - High-performance HTTP server, reverse proxy, and also IMAP/POP3/SMTP proxy server.
- nmap - Network Mapper, a free and open-source utility for network discovery and security auditing.
- nodejs - Asynchronous event-driven JavaScript runtime, built on Chrome's V8 engine.
- numpy - Fundamental package for scientific computing with Python.
- nvm - Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions.
- ollama - Tool to run large language models (LLMs) like Llama 2 locally.
- openjdk - Open source implementation of the Java Platform, Standard Edition (JDK).
- pandoc - Universal document converter, capable of converting between many markup formats.
- pipx - Tool to install and run Python applications in isolated environments, managing their dependencies.
- pnpm - Fast, disk space efficient package manager for Node.js projects.
- podman - Daemonless container engine for developing, managing, and running OCI Containers on Linux (can be used on macOS via VM).
- poetry - Python dependency management and packaging tool, helps manage project libraries and virtual environments.
- postgresql - Powerful, open source object-relational database system (server & client).
- pre-commit - A framework for managing and maintaining multi-language pre-commit hooks for Git.
- pyenv - Simple Python version management tool, allows switching between multiple Python versions.
- qemu - Generic and open source machine emulator and virtualizer.
- rbenv - Tool to manage multiple Ruby versions installed side-by-side.
- ripgrep - Line-oriented search tool that recursively searches directories for a regex pattern, faster than grep.
- ruby - Dynamic, open source programming language with a focus on simplicity and productivity.
- ruby-build - Tool to compile and install different versions of Ruby, often used with rbenv.
- rust - Systems programming language focused on safety, speed, and concurrency.
- sops - Editor of encrypted files that supports YAML, JSON, ENV, INI and BINARY formats, integrating with KMS, GPG, etc.
- subversion - Enterprise-class centralized version control system (SVN).
- telnet - User interface to the TELNET protocol for remote terminal connections.
- trivy - Security scanner for vulnerabilities, misconfigurations, secrets, SBOM in containers, K8s, code repositories, etc.
- unbound - Validating, recursive, and caching DNS resolver.
- virtualenv - Tool to create isolated Python environments.
- watchman - File watching service developed by Facebook, triggers actions on file changes.
- wangle - Facebook C++ library providing abstractions for asynchronous client/server transport protocols.
- yarn - Fast, reliable, and secure dependency management for JavaScript projects (alternative to npm).
- yt-dlp - Command-line program to download videos from YouTube and many other sites (fork of youtube-dl).
- zoxide - A smarter cd command for your shell, learns your frequently used directories.
- zsh - A shell designed for interactive use, although it is also a powerful scripting language.

Obviously, zig and rust-based tools are not possible to port at this time.

**Comment by IgorTodorovskiIBM** [comment]
Comparing to the list of validated open source Linux on Z projects (https://community.ibm.com/zsystems/oss/), here's what's missing:

- Alfresco: An open-source enterprise content management (ECM) system for documents, web content, records, images, etc.
- Ansible: An open-source automation tool for configuration management, application deployment, task automation, and orchestration. (Playbooks can target z/OS, but the core engine usually runs elsewhere).
- AntLR: A parser generator tool used for reading, processing, executing, or translating structured text or binary files (often used for building language compilers/interpreters).
- Apache ActiveMQ: An open-source message broker that supports multiple messaging protocols (like AMQP, MQTT, STOMP) for integrating applications.
- Apache Camel: An open-source integration framework based on known Enterprise Integration Patterns, used to integrate various systems consuming or producing data.
- Apache Cassandra: A highly scalable, distributed NoSQL wide-column store database designed for high availability and fault tolerance.
- Apache CouchDB: An open-source NoSQL document database that uses JSON for documents, JavaScript for MapReduce queries, and HTTP for an API.
- Apache Geode: A high-performance, distributed in-memory data grid for high-volume, low-latency applications.
- Apache HBase: An open-source, distributed, versioned, non-relational database modeled after Google's Bigtable, running on top of HDFS (Hadoop Distributed File System).
- Apache HTTP Server: The widely-used open-source web server software known for its power and flexibility. (Note: IBM HTTP Server is based on Apache but is a distinct product).
- Apache Ignite: A distributed database, caching, and processing platform designed for transactional, analytical, and streaming workloads at scale.   
- Apache JMeter: An open-source Java application designed to load test functional behavior and measure performance of web applications and other services.
- Apache Mesos: An open-source cluster manager that provides efficient resource isolation and sharing across distributed applications or frameworks.   
- Apache Solr: An open-source enterprise search platform built on Apache Lucene, providing powerful full-text search, faceted search, and real-time indexing.
- Apache Spark: A fast and general-purpose cluster computing system for big data processing, supporting various workloads like batch, interactive queries, streaming, and machine learning. (Note: IBM provides Spark for z/OS separately).
- Apache Storm: An open-source distributed real-time computation system for processing streams of data, similar to Hadoop MapReduce but for real-time processing.
- Apache Tomcat: An open-source implementation of the Java Servlet, JavaServer Pages, Java Expression Language, and Java WebSocket specifications; a popular Java web server and servlet container.   
- Apache Zeppelin: A web-based notebook that enables data-driven, interactive data analytics and collaborative documents with SQL, Scala, Python, R and more.   
- Apache ZooKeeper: A centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services for distributed systems.   
- Beats (Elastic Beats): A platform for single-purpose data shippers; they send data from hundreds or thousands of machines and systems to Logstash or Elasticsearch.
- cAdvisor (Container Advisor): Provides container users an understanding of the resource usage and performance characteristics of their running containers.   
- Calico: An open-source networking and network security solution for containers, virtual machines, and native host-based workloads.   
- Chef Infra Client: An automation tool that turns infrastructure into code, used for configuration management and deployment.
- CockroachDB: A distributed SQL database built for cloud-native applications, providing scalability, resilience, and consistency.
- Consul: A service mesh solution providing a full-featured control plane with service discovery, configuration, and segmentation functionality.   
- CoreDNS: A flexible, extensible DNS server that can serve as the Kubernetes cluster DNS.
- Couchbase: A distributed NoSQL cloud database offering high performance for interactive applications.
- Cruise Control: A tool developed at LinkedIn to fully automate the dynamic workload rebalancing and healing of Apache Kafka clusters.
- Docker Compose: A tool for defining and running multi-container Docker applications using a YAML file to configure the application's services. (Generally used via zCX on z/OS).   
- Docker Distribution (Registry): An open-source system for storing and distributing Docker images (the backend for Docker Hub). (Generally used via zCX on z/OS).
- Docker-CE (Community Edition): The open-source containerization platform for building, shipping, and running distributed applications. (Generally used via zCX on z/OS).
- Drupal: An open-source content management system (CMS) used for building websites and online applications.
- Elasticsearch: A distributed, RESTful search and analytics engine capable of solving a growing number of use cases.
- Envoy: An open-source edge and service proxy, designed for cloud-native applications (often used in service meshes like Istio).
- Erlang: A general-purpose, concurrent, functional programming language and runtime system known for fault tolerance and distributed systems.
- etcd: A distributed, reliable key-value store used for the shared configuration and service discovery, notably as Kubernetes' primary datastore.
- flannel: A simple and easy way to configure a layer 3 network fabric designed for Kubernetes.
- Fluentd: An open-source data collector for unified logging layer, allowing unification of data collection and consumption.
- GlusterFS: An open-source, distributed, scalable network file system suitable for data-intensive tasks.
- HAProxy: A free, very fast and reliable reverse-proxy offering high availability, load balancing, and proxying for TCP and HTTP-based applications.   
- Helm: The package manager for Kubernetes, helping define, install, and upgrade complex Kubernetes applications.
- Hibernate: A popular object-relational mapping (ORM) framework for Java, simplifying database access in Java applications.
- Htop: An interactive process viewer for Unix systems, offering a more user-friendly alternative to the standard top command.
- InfluxDB: An open-source time series database (TSDB) optimized for fast, high-availability storage and retrieval of time series data.
- Jenkins: An open-source automation server used to build, test, and deploy software, enabling continuous integration and continuous delivery (CI/CD).
- Joomla: An open-source content management system (CMS) for publishing web content.
- K8s CSI components (Container Storage Interface): Standard components enabling storage vendors to develop plugins exposing storage systems to container orchestration systems like Kubernetes.
- Keystone (Openstack): The identity service project within the OpenStack cloud computing platform, providing API client authentication, service discovery, and distributed multi-tenant authorization.
- Kibana: An open-source data visualization dashboard for Elasticsearch, providing visualization capabilities on top of the content indexed on an Elasticsearch cluster.   
- Kind (Kubernetes in Docker): A tool for running local Kubernetes clusters using Docker container "nodes".   
- Kube Router: A turnkey solution for Kubernetes networking, providing CNI networking, network policy enforcement (using IPVS/LVS, BGP, and iptables/ipset).
- Kubernetes: An open-source system for automating deployment, scaling, and management of containerized applications. (Generally run via zCX or Linux on Z).
- Kubernetes Minikube: A tool that runs a single-node Kubernetes cluster locally inside a virtual machine or container for development and testing.
- Libunwind: A portable C library to determine the call-chain of a program.
- Logstash: An open-source server-side data processing pipeline that ingests data from multiple sources simultaneously, transforms it, and then sends it to a "stash" like Elasticsearch.   
- LuaJIT: A Just-In-Time compiler for the Lua programming language, significantly speeding up Lua code execution. 
- Magento: An open-source e-commerce platform written in PHP.
- MariaDB: A community-developed, commercially supported fork of the MySQL relational database management system.
- MongoDB: A popular source-available cross-platform document-oriented NoSQL database program. 
- MongoDB Drivers: Client libraries needed for applications written in various languages (Java, Python, Node.js, etc.) to connect to a MongoDB database.
- MySQL: One of the world's most popular open-source relational database management systems (RDBMS).
- Neo4j: A highly scalable native graph database that leverages data relationships as first-class entities.
- NGINX: A high-performance web server, reverse proxy, load balancer, mail proxy, and HTTP cache. (Commonly run via zCX on z/OS).
- oCaml: A general-purpose, industrial-strength programming language with an emphasis on expressiveness and safety (functional, imperative, object-oriented).
- OPA (Open Policy Agent): An open-source, general-purpose policy engine that enables unified, context-aware policy enforcement across the stack.   
- OpenResty: A web platform based on NGINX and LuaJIT, extending NGINX with Lua scripting capabilities.
- PM2: A production process manager for Node.js applications with a built-in load balancer.
- PostgreSQL: A powerful, open-source object-relational database system known for reliability, feature robustness, and performance.
- Puppet: An open-source software configuration management tool which uses its own declarative language to describe system configuration.
- PyPy: An alternative implementation of the Python programming language, often providing significant speed improvements via its Just-in-Time compiler.
- R: A free software environment for statistical computing and graphics.
- RabbitMQ: An open-source message broker software (sometimes called message-oriented middleware) that implements the Advanced Message Queuing Protocol (AMQP). (Note: zopen has librabbitmq, a client library).   
- Rails (Ruby on Rails): A server-side web application framework written in Ruby, following the model–view–controller (MVC) pattern.
- RethinkDB: An open-source, distributed document-oriented database that stores JSON documents and pushes updates to applications in real-time.
- RocksDB: A high-performance embedded key-value database library developed by Facebook, optimized for fast storage media like SSDs.
- Ruby: A dynamic, open-source programming language with a focus on simplicity and productivity.
- Salt (SaltStack): An open-source automation and configuration management software based on Python.
- Scala: A general-purpose programming language providing support for functional programming and a strong static type system, designed to run on the Java Virtual Machine (JVM).   
- ScyllaDB: An open-source distributed NoSQL wide-column store database designed to be compatible with Apache Cassandra while achieving higher throughput and lower latencies.
- Snappy-Java: A Java port of Google's Snappy compression/decompression library.
- Sonarqube: An open-source platform for continuous inspection of code quality to perform automatic reviews with static analysis of code to detect bugs, code smells, and security vulnerabilities.   
- Spire: An open-source toolchain for establishing trust between software systems using platform attestors and cryptographic identities (part of the SPIFFE standard).
- StatsD: A simple network daemon that listens for statistics, like counters and timers, sent over UDP or TCP and sends aggregates to pluggable backend services (e.g., Graphite, InfluxDB).
- Strimzi Kafka: Provides a way to run an Apache Kafka cluster on Kubernetes in various deployment configurations.
- Sysdig: A universal system visibility tool with native support for containers, providing monitoring, security, and troubleshooting capabilities.
- TensorFlow: An end-to-end open-source platform for machine learning, developed by Google.
- TensorFlow Serving: A flexible, high-performance serving system for machine learning models, designed for production environments.   
- TensorFlow Transform: A library for TensorFlow that allows users to preprocess input data for machine learning models.
- V8 JavaScript: Google's open-source high-performance JavaScript and WebAssembly engine, written in C++. (Used in Chrome and Node.js).
- WildFly (JBoss): An open-source Java EE application server developed by Red Hat.
- Word2Vec: A group of related models used to produce word embeddings (vector representations of words) for natural language processing tasks.
- WordPress: A free and open-source content management system (CMS) based on PHP and MySQL, widely used for websites and blogs.
- XMLSec: A library providing implementation of XML Signature and XML Encryption standards.
- Zabbix: An open-source monitoring software tool for diverse IT components, including networks, servers, virtual machines, and cloud services.   
- Zerotier: A platform that creates secure, manageable, and scalable private networks between devices anywhere in the world.

**Comment by IgorTodorovskiIBM** [comment]
Here's the related poll + results so far: https://github.com/orgs/zopencommunity/discussions/1019
